// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQWyPp8k5lteX41T0xwN11qHkEvcKU6Ro',
    appId: '1:941722700823:web:922cf2a393f684990fa052',
    messagingSenderId: '941722700823',
    projectId: 'flutterapp-df3f2',
    authDomain: 'flutterapp-df3f2.firebaseapp.com',
    storageBucket: 'flutterapp-df3f2.appspot.com',
    measurementId: 'G-HJ8HFX9EC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkr_XUk3dKUIlZ9X-Uc5Ey64K_1cEw7-E',
    appId: '1:941722700823:android:96d884fc40da98c20fa052',
    messagingSenderId: '941722700823',
    projectId: 'flutterapp-df3f2',
    storageBucket: 'flutterapp-df3f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxhIwXC2_m_qx2LSuR8ZIKuHEsp4-AfHs',
    appId: '1:941722700823:ios:9ec223cbd6cccae50fa052',
    messagingSenderId: '941722700823',
    projectId: 'flutterapp-df3f2',
    storageBucket: 'flutterapp-df3f2.appspot.com',
    iosClientId: '941722700823-0rv4jb41s6vkqukfv7hdod0ted1p0i8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.apisteam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxhIwXC2_m_qx2LSuR8ZIKuHEsp4-AfHs',
    appId: '1:941722700823:ios:9ec223cbd6cccae50fa052',
    messagingSenderId: '941722700823',
    projectId: 'flutterapp-df3f2',
    storageBucket: 'flutterapp-df3f2.appspot.com',
    iosClientId: '941722700823-0rv4jb41s6vkqukfv7hdod0ted1p0i8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.apisteam',
  );
}
*/